FROM morrisalp/base

ADD launch_jl.sh /root

RUN chmod a+x /root/launch_jl.sh

EXPOSE 8888

ENTRYPOINT ["/root/launch_jl.sh", "$KERNEL_ENVS_DIR"]
# submit with environment variable KERNEL_ENVS_DIR set to add environments from directory as kernels
